/*! Generated by redux-scfld */
import { Storage } from '../../../../commons/browser';

export default function (getState) {
  const { config } = getState();
  return Storage
    .get('config')
    .then(loadedConfig => Storage.set('config', { ...config, ...loadedConfig }))
    .then(() => Storage.get('config'))
}
