/*! Generated by redux-scfld */
import { Storage } from '../../../../commons/browser';

export default function (getState, newConfig) {
  const { config } = getState();
  return Storage
    .set('config', { ...config, ...newConfig })
    .then(() => Storage.get('config'));
}
