/*! Generated by redux-scfld not for editing */

// Statuses
export const STATUS_PROCESS = 'STATUS_PROCESS';
export const STATUS_SUCCESS = 'STATUS_SUCCESS';
export const STATUS_FAILURE = 'STATUS_FAILURE';

// Generated Namespaces
export const NAMESPACE_CONFIG = 'config';
export const NAMESPACE_PARAMS = 'params';

export const NAMESPACES = [
  NAMESPACE_CONFIG,
  NAMESPACE_PARAMS,
];
// Generated Types
export const CONFIG_LOAD = 'CONFIG_LOAD';
export const CONFIG_SET = 'CONFIG_SET';
export const PARAMS_RESET = 'PARAMS_RESET';
export const PARAMS_SET = 'PARAMS_SET';
